### ISSUE TITLE
Remove VOLUME directive

### ISSUE THREAD

**Issue by ericjacolin** [BirgerK/docker-apache-letsencrypt#11]
I needed to bind the container Apache virtual host configuration and the Apache and certbot log file locations from a persistent disk instead of volumes, which is what one typically wants to do on a production environment
```
services:
    apache-proxy:
        build:
            context: "docker-apache-letsencrypt"
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "${PDISK_MNT}/etc/letsencrypt:/etc/letsencrypt"
            - "${PDISK_MNT}/etc/apache-proxy/sites-enabled:/etc/apache2/sites-enabled"
            - "${PDISK_MNT}/log/letsencrypt:/var/log/letsencrypt"
            - "${PDISK_MNT}/log/apache-proxy:/var/log/apache2"
```
Since it is not possible to override a parent VOLUME directive, I could not extend the image but had to clone the Dockerfile and remove the VOLUME directive, which is not ideal.
Removing the VOLUME directive would give more flexibility to users.
