### ISSUE TITLE
Cannot start service certbot

### ISSUE THREAD

**Issue by dfsoeten** [BirgerK/docker-apache-letsencrypt#8]
Hey, I'm trying to include this in my personal project to automatically setup SSL with docker & docker-compose. 

When I try to start my containers with `docker-compose -f docker-compose.yml -f docker-compose.production.yml up` I get the following error: `ERROR: for certbot  Cannot start service certbot: network <hash> not found`. 

I put the following in my `docker-compose.production.yml` file: 

```
certbot:
        image: birgerk/apache-letsencrypt
        environment:
            - "DOMAINS=${DOMAIN_NAME},www.${DOMAIN_NAME}"
            - "WEBMASTER_MAIL=${MAIL_ADDRESS}"
```

Do you have any idea what I could be doing wrong?
